version: '3'

services:
  filebeat:
    hostname: filebeat
    image: test-filebeat
    build:
      context: filebeat
      dockerfile: Dockerfile
    volumes:
      # needed to access all docker logs (read only) :
     - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
     - "/var/run/docker.sock:/var/run/docker.sock"
    links:
       - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.2
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - "5601:5601"
#  logstash:
#    hostname: logstash
#    image: test-logstash
#    build:
#      context: logstash
#      dockerfile: Dockerfile
#    ports:
#      - 5044:5044
#    environment:
#      LOG_LEVEL: error
#    links:
#      - elasticsearch
  elasticsearch:
    hostname: elasticsearch
    image: test-elasticsearch
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
